### ISSUE TITLE
rusEFI change

### ISSUE THREAD

**Issue by rusefillc** [gengyong/luaaa#5]
no action really required but FYI-ish, we had to implement the following change for luaaa to compile in our environment

https://github.com/rusefi/luaaa/commit/499699790e6064e2f536fe5bdbff715a8cf1e5c2

**Comment by gengyong** [comment]
fixed in updated version, could you please have a try?

**Comment by gengyong** [comment]
there is a fatal bug under clang: parameter order is inverse when call c++ exported function.
it was fixed just now, if you are using clang as compiler, please merge to new version.

**Comment by rusefillc** [comment]
No, rusEFI still does not compile with luaaa as is with gcc

I have https://github.com/rusefi/luaaa is currently even with gengyong:master.

I have https://github.com/rusefi/rusefi/tree/on_luaaa_master branch pointing at https://github.com/rusefi/luaaa

you can see github actions failure messages at https://github.com/rusefi/rusefi/runs/3797339354

**Comment by gengyong** [comment]
it seems you are using c compiler(gcc) instead of c++ compiler(g++). try add link option '-lstdc++' to compiler options.

**Comment by gengyong** [comment]
> it seems you are using c compiler(gcc) instead of c++ compiler(g++). try add link option '-lstdc++' to compiler options. 

or remove any reference to c++ std lib from luaaa, and replace 'new' with malloc, replace 'delete' with free(or any other your custom memory allocators).

**Comment by gengyong** [comment]
> > 2). new operator is basic requirement for c++ codes
> 
> this is not true - C++ makes no requirement that you use dynamic allocation, nor does it require that you use the stl.
> 
> > 3). default implementation of lua userdata allocator alloc mem from heap
> > 4). alloc object from lua userdata do not eliminate the requirement of heap because malloc are using in luaaa
> 
> Again, this is not necessarily true. When you configure the lua VM, you pass in an allocator function. In our case, that allocator allocates from a static heap, and does not call standard `malloc`/`free`/`new`/`delete`.

in fact the real reason for that alloc memory by new operator instead of alloc by lua userdata is it's hard to check where the object comes from so we can know how to  extract it from lua stack. 
new operator used commonly everywhere so I don't think this requirement is too strict to c++ users,  anyway you are right if users are writing codes for embedded device this requirement is too tough, yes I'll try to remove the memory alloc new from luaaa, maybe in next few days.
